class Spree::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  include Spree::Core::ControllerHelpers::Common
  include Spree::Core::ControllerHelpers::Order
  include Spree::Core::ControllerHelpers::Auth
  include Spree::Core::ControllerHelpers::Store
  include Rails.application.routes.url_helpers

  class << self
    def provides_callback_for(*providers)
      providers.each do |provider|
        define_method(provider) { omniauth_callback }
      end
    end
  end

  Spree::SocialConfig.providers.keys.each do |provider|
    provides_callback_for provider
  end

  def omniauth_callback
    if request.env['omniauth.error'].present?
      flash[:error] = I18n.t('devise.omniauth_callbacks.failure', kind: auth_hash['provider'], reason: I18n.t('spree.user_was_not_valid'))
      redirect_back_or_default(root_url)
      return
    end

    authentication = Spree::UserAuthentication.find_by_provider_and_uid(auth_hash['provider'], auth_hash['uid'])
    session[:oauth_provider] = auth_hash['provider']

    if authentication.present? and authentication.try(:user).present?
      user = authentication.user
      if user.partner?
        flash[:notice] = I18n.t('devise.omniauth_callbacks.success', kind: auth_hash['provider'])
        sign_in_and_redirect :spree_user, user
      else
        # make sure signup_cookie equal existing user token
        cookies.permanent[:signup_token] = user.signup_token

        redirect_to signup_step_path(step: user.state_name)
      end
    elsif spree_current_user
      redirect_back_or_default(root_url)
    else
      # new authentication

      email = auth_hash['info']['email']
      existing_user = Spree.user_class.find_by_email(email)
      if existing_user && existing_user.partner?
        flash[:error] = I18n.t('devise.omniauth_callbacks.existing_partner', email: email)
        redirect_to partner_login_path
      elsif existing_user
        # make sure signup_cookie equal existing user token
        cookies.permanent[:signup_token] = existing_user.signup_token

        # populate user info
        existing_user.apply_omniauth(auth_hash)
        existing_user.save

        redirect_to signup_step_path(step: existing_user.state_name)
      else
        token = set_signup_token
        user = generate_new_user

        # populate user info
        user.apply_omniauth(auth_hash)
        user.save

        redirect_to signup_step_path(step: 'name')
      end
    end
  end

  def failure
    set_flash_message :error, :failure, kind: failed_strategy.name.to_s.humanize, reason: failure_message
    redirect_to spree.login_path
  end

  def passthru
    render file: "#{Rails.root}/public/404", formats: [:html], status: 404, layout: false
  end

  def auth_hash
    request.env['omniauth.auth']
  end

  private

  def set_signup_token
    cookies[:signup_token].presence || cookies.permanent[:signup_token] = SecureRandom.hex
  end

  def generate_new_user
    user = Spree::User.find_or_init_by_token(cookies[:signup_token])
    user.email = nil if user.email_autogenerated?
    user
  end
end
